// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnQIKyxHvcj3w7rYRHPbneEP40PRPuark',
    appId: '1:670124011120:web:5f7e2cecc62f9509878eb5',
    messagingSenderId: '670124011120',
    projectId: 'app-crud-990f4',
    authDomain: 'app-crud-990f4.firebaseapp.com',
    databaseURL: 'https://app-crud-990f4-default-rtdb.firebaseio.com',
    storageBucket: 'app-crud-990f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXjkqQu1q84vB9vKFmRPxCit-vBEPmQBI',
    appId: '1:670124011120:android:e1678e61e3448ebf878eb5',
    messagingSenderId: '670124011120',
    projectId: 'app-crud-990f4',
    databaseURL: 'https://app-crud-990f4-default-rtdb.firebaseio.com',
    storageBucket: 'app-crud-990f4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3yVAem0y7f5Iiqkn7H9OgTjtOH_SWghg',
    appId: '1:670124011120:ios:f71cd64ebc6b4cce878eb5',
    messagingSenderId: '670124011120',
    projectId: 'app-crud-990f4',
    databaseURL: 'https://app-crud-990f4-default-rtdb.firebaseio.com',
    storageBucket: 'app-crud-990f4.firebasestorage.app',
    iosBundleId: 'com.example.app12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3yVAem0y7f5Iiqkn7H9OgTjtOH_SWghg',
    appId: '1:670124011120:ios:f71cd64ebc6b4cce878eb5',
    messagingSenderId: '670124011120',
    projectId: 'app-crud-990f4',
    databaseURL: 'https://app-crud-990f4-default-rtdb.firebaseio.com',
    storageBucket: 'app-crud-990f4.firebasestorage.app',
    iosBundleId: 'com.example.app12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnQIKyxHvcj3w7rYRHPbneEP40PRPuark',
    appId: '1:670124011120:web:8b328f5b314bee45878eb5',
    messagingSenderId: '670124011120',
    projectId: 'app-crud-990f4',
    authDomain: 'app-crud-990f4.firebaseapp.com',
    databaseURL: 'https://app-crud-990f4-default-rtdb.firebaseio.com',
    storageBucket: 'app-crud-990f4.firebasestorage.app',
  );
}
